typography_spectrum: 0.8388551485259086
color:
  brandStrength: 0.6908307834528387
  lightness: 0.8310630430933088
  saturation: 0.10606530960649252
  rhythmicContrast: 0.5597252286970615
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.6926660528406501
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/efdbace0-38db-45da-8e68-78b34468cbb0.jpg
name: squire/testsite
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8d4ed2c7-49aa-4ecc-b3cf-9e6acc2cb11d.png
title: Systems cueing you & I are electronic.
description: Your equal.
